ministryofjustice/hmpps-nomis-prisoner-api

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Offender.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderBooking.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderVisitBalance.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBookingBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/VisitBalanceBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/VisitResourceIntTest.kt
Next steps 
1) Load PERSON (and contacts)
2) Change Repository tests to use builder
3) Add more tests around person and contacts
=> SDI-24 Offender booking entity builder

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/data/VisitResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AgencyLocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AgencyLocationType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/CourtType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderBooking.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/ReferenceCode.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Visit.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/VisitResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBookingBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderContactBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/VisitBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/VisitRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/VisitResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/service/VisitServiceTest.kt
removed optionals to match db non nullable columns
=> SDI-44 get visit endpoint

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/data/CreateVisitRequest.kt
=> Sdi 59 fix prisoner api time swagger

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
- SDI-296 Upgrade to latest Gradle plugin
- SDI-296 Upgrade to gradlew 7.5
=> mh SDI 296 spring boot 2.7.2

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/VisitResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/service/VisitServiceTest.kt
Description needs to follows NOMIS idioms while being able to describe the room and open closed state.
`
"Main visit room" for open visits become HEI-VSIP-MAIN-SOC 
"Main visit room" for closed visits become HEI-VSIP-MAIN-CLO
`
=> SDI-305 New algorithm for generating NOMIS description for a given room

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/data/CreateIncentiveRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/IncentivesResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/service/IncentivesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/IncentivesResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/service/IncentiveServiceTest.kt
=> SDI-360 Update Nomis from incentive creation domain event

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/data/UpdateVisitRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Visit.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/VisitResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/VisitResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/service/VisitServiceTest.kt
* Allows updates to the visitor list
TODO all other mutable fields
=> SDI-385 Add update visit

src/main/resources/db/migration/V1_1001__V_OFFENDER_VISITS.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/VisitResourceIntTest.kt
NOMS uses the v_offender_visits to read visits, the update needs to be compatible with that view, so add a version of the view and tests to assert the fields not read by API is also updated correctly
=> SDI-385 Added test on view that NOMSI uses

helm_deploy/hmpps-nomis-prisoner-api/Chart.yaml, helm_deploy/hmpps-nomis-prisoner-api/values.yaml, helm_deploy/values-dev.yaml
increase-pod-disruption-budget
=> increase-pod-disruption-budget

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/ActivitiesResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/service/ActivitiesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/service/ActivitiesServiceTest.kt
=> SDI-499 Create activity API

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/config/NomisPrisonerApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/data/CreateActivityRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/data/CreateVisitRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/data/UpdateVisitRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderSentenceAdjustment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderSentenceAdjustmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderSentenceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/SentenceAdjustmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/SentenceCalculationTypeRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/SentenceAdjustmentResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/service/SentenceAdjustmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBookingBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/SentenceBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/SentenceAdjustmentsResourceIntTest.kt
TODO:
More tests showing multiple sentences
More tests on the side effects of the adjustment
More tests defaults 
Maybe improve the mapping to remove double mapping
More tests for GET endpoint
=> SDI-536 Basic creation of sentence adjustment

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/UpdateActivityRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/config/NomisPrisonerApiExceptionHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivitiesResourceIntTest.kt
And add in some tests for handling bad data in the request object. I may delete some of these tests later, for now I just want to know the API is robust.
=> SDI-500 Flesh out the amend activities request

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivitiesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/CourseActivity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivitiesResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/CourseActivityBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/CourseActivityPayRateBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/ProgramServiceBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/ActivityRepositoryTest.kt
Preparation for writing lots of update activity tests. Builder pattern seems standard in the rest of the app..
=> SDI-500 activity builders

helm_deploy/hmpps-nomis-prisoner-api/values.yaml
a recent nginx ingress upgrade needs an explicit ingress class to ensure continued compatibility
=> Compatibility fix for nginx

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivitiesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/CreateOffenderProgramProfileRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderProgramProfile.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderProgramProfilePayBand.kt, src/main/resources/db/migration/V1_97__OFFENDER_PRG_PRF_PAY_BANDS.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivitiesResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivitiesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt
add creation of OffenderProgramProfilePayBand
=> SDI-501 Allocate offender API

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderSentenceAdjustment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentenceAdjustmentsResourceIntTest.kt
- Assume all data will be resent
- Assume booking and sentence relationship can not change
=> ll SDI-549 Update to sentence adjustment

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivitiesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderProgramProfile.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderProgramProfilePayBand.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderProgramProfileRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivitiesResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderProgramProfileBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderProgramProfilePayBandBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt
This validation occurs in Nomis so we should do the same in our Nomis update API.
=> SDI-500 Prevent deletion of pay rate if allocated to an offender

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderKeyDateAdjustment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/KeyDateAdjustmentsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentenceAdjustmentsResourceIntTest.kt
also made language consistent with adjustment IDs
=> SDI-549 Update to key date adjustment

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivitiesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/UpdateActivityRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/CourseActivity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivitiesResourceIntTest.kt
But the details of what else should change and what should happen on a change need defining (e.g. does an end date end all of the pay rates and deallocate all prisoner from that date?) and will be covered on SDI-599
=> SDI-500 Limit the update request to what we know will need updating

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentenceAdjustmentsResourceIntTest.kt
* TODO add telemetry to all API calls with tests
=> SDI-543 Delete sentence adjustment

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/PayRatesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/CourseActivity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/CourseActivityPayRate.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/PayRateServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/CourseActivityBuilder.kt
Publishing telemetry for activity schedule and pay rates - still need to do schedule rules
=> SDIT-651 update activity metrics

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderCourseAttendance.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderCourseAttendanceBuilder.kt
And add validation to prevent updates if already paid in Nomis
=> SDIT-690 add telemetry for upsert attendance

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/incentives/IncentivesResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/incentives/IncentivesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/IncentiveRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/incentives/IncentivesResourceIntTest.kt
NOMIS use an algorithm where the current IEP level is determined by the latest sequence on the latest date. Therefore an IEP with a time greater than the current IEP can exist.
There is an edge case where the synchronisation from DPS causes a later Incentive to be created before less recent on, meaning NOMIS thinks the 2nd to last one is current since it will have the higher sequence.
This endpoint to be used in emergencies and correct this data to reorder IEPs so the ones with the latest time has the highest sequence.
=> SDIT-833 Admin endpoint for IEP sequence data correction

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/appointments/AppointmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/appointments/AppointmentsResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/appointments/AppointmentsResourceIntTest.kt
Ability to undo a cancellation
=> SDIT-855 Appointments un-cancel event

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivitiesResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderCourseAttendance.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceResourceIntTest.kt
New endpoint allows update of attendance date and times by using course schedule ID as the key.
=> SDIT-836 Add replacement upsert attendance endpoint

src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/DSL.kt
Added single annotation to restrict scope to single level but kept method annotation to make methods as DSL methods
=> SDIT-856 Add DSL scope

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AllocationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderProgramProfilePayBand.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderProgramProfileRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AllocationResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt
But continue to prevent create of allocation in wrong prison
=> SDIT-843 Allow updates to allocations if in different prison

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderProgramProfile.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderProgramProfileBuilder.kt
But prevent these if creating an attendance
=> SDIT-843 Allow update attendance in wrong prison or allocation ended

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitServiceTest.kt
NOMIS treats a hyphen as a hierarchy indicator
=> SDIT-905 VSIP room code must use underscore

src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AllocationResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/CourseActivityBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/DSL.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBookingBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderProgramProfileBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/ProgramServiceBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt
Course allocations (or OffenderProgramProfiles) can be children of either offender bookings or course activities (as per their JPA mappings) rather than a top level entity.
=> SDIT-902 Refactor course allocation DSL

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceResourceIntTest.kt
There is a screen in Nomis called Internal Movements which can be used to confirm an internal movement (such as an attendance) and sets the event status to COMP. This is separate to marking of the attendance and shouldn't be overridden.
=> SDIT-911 Don't overwrite a confirmed attendance

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationFilter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsResourceIntTest.kt
* just skeleton so we define the interface
=> SDIT-926 Skeleton GET /adjudications/ids resource

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationIncidentParty.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/AdjudicationIncidentPartyRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/specification/AdjudicationSpecification.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/AdjudicationIncidentBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/DSL.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt
* Can filter a list of adjudications by fromDate, toDate and a list of prisons
=> SDIT-926 GET /adjudications/ids resource

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationIncident.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationIncidentParty.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt
TODO
* Other parties involved in incident
* Repairs
* Evidence
* Assert core adjudication values are correct with more tests
=> SDIT-873 Basic simple adjudication creation

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/CreateAdjudicationRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationIncident.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/AdjudicationIncidentPartyRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsResourceIntTest.kt
* Evidence creation
* Better validation
* Better tests around validation errors
* Minor refractor in the service to improve readability
=> SDIT-873 Better validation and evidence creation

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/CreateAdjudicationRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt
* Also improved swagger examples and removed deprecated `required`
=> SDIT-873 Add staff witnesses to adjudication incident

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationIncident.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/AdjudicationIncident.kt
CREATE_USER_ID is username not staff id
=> SDIT-969 Corrected mapping of create user

src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/MigrationResourceIntTest.kt
=> SDIT-980 Test paging implemented correctly

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/AdjudicationHearingResult.kt
DPS needs parent connective award adjudication number
=> SDIT-927 Add adjudication number to consecutive award

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivitiesResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AllocationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityServiceTest.kt
To be used after migrating Nomis activities to DPS.
=> SDIT-1043 Api to end activities and allocations

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Address.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationHearing.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationHearingResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationHearingResultAward.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationIncidentParty.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AgencyInternalLocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AgencyLocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderProgramProfile.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderVisitBalanceAdjustment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Phone.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/VisitOrder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/AdjudicationHearingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/AdjudicationIncidentPartyRepository.kt
- Add entity graph for adjudication and hearings
- Fix issue with abstract classes and open properties preventing use of proxy
- Fix warnings for Lazy Loading and illegal Not Found combination
TODO
- Continue with entity graph
- Investigate why lazy loading is not working on so many properties
=> SDIT-1072 Entity graph for adjudication and fix JPA warnings

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderNonAssociationDetailRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationsResourceIntTest.kt
=> SDIT-1081 Close non-association

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationsResourceIntTest.kt
=> SDIT-1080 Amend non-associaton

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderNonAssociation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderNonAssociationDetail.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationsResourceIntTest.kt
=> SDIT-1082 Delete non-association

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/specification/NonAssociationSpecification.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationResource.kt
Change ordering to use nomsId, not numerical id
=> SDIT-997 Add migration endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationService.kt
Add Audit for NAs to generate DPS_SYNCHRONISATION value
=> SDIT-996 Add sync service from Nomis

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderNonAssociationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationsResourceIntTest.kt
Order NA prisoner pairs by id, not nomsId
=> SDIT-1096 Non-association Reconciliation process

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/CreateHearingResultAwardResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsHearingResultAwardResourceIntTest.kt
=> SDIT-883 Create award returns the sanction sequence

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/config/NomisPrisonerApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/data/Exceptions.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderCourseAttendance.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceResourceIntTest.kt
So that the client can react to this specific error case
=> SDIT-1152 Return an error code when trying to update a paid attendance

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/HearingResultAwardRequests.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsHearingResultAwardResourceIntTest.kt
* TODO - another integration tests showing when awards are out of sync with unquash
=> SDIT-1190 adjudication unquash endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderBooking.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBooking.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderExternalMovement.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderSentence.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderSentenceAdjustment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentsResourceIntTest.kt
Introduced a 'hasBeenReleased' flag to SentencingAdjustmentResource to indicate if a prisoner has been released for a specific booking. This new field is mandatory and required adjustments in the corresponding entity OffenderBooking and related tests. Also, release logic added in the OffenderBooking helper builder.
=> SDIT-1428 Add release flag to SentencingAdjustmentResource

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/CourtEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/CourtEventCharge.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
Moving to new update structure to allow lists for update and create offender charges.
=> SDIT-1369 update existing appearances

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AlertWorkFlow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderAlert.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/WorkFlow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/WorkFlowLogRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderAlert.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/WorkFlowLog.kt
WorkFlow for an Alert changed to OneToMany since there is a small but significant amount of bad data in NOMIS where alert has no workflows or more than one
=> SDIT-1483 Changed WorkFlow to OneToMany

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderAlertRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderAlert.kt, src/test/resources/application-test.yml
The changes include a new feature to retrieve alert data by booking ID and alert sequence. An endpoint is added for this feature along with its security and access roles. The code also encompasses creation of new classes to support the alert object and the audit details. This facilitates retrieval of detailed audit information for each alert. Tests are included for validating successful retrieval and various fail cases.
=> SDIT-1483 Add alert retrieval with audit data

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt
When not proceeding with an old adjudication that occurred at a prison that is now closed the adjudication room may no longer be active. In this edge case allow the room to be "used" for a dummy hearing that is required to add a result.
=> SDIT-1506 Allow inactive adjudication rooms to be used.

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/appointments/AppointmentsResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AgencyInternalLocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/CreateLocationRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/DeactivateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/LocationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/LocationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/UpdateCapacityRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/UpdateCertificationRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/UpdateLocationRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/AgencyInternalLocation.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/NomisData.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/LocationsResourceIntTest.kt
Update, de/re-activate and change capacity and certification
=> SDIT-1499 Nomis api update endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/incidents/IncidentResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/incidents/IncidentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/incidents/QuestionnaireResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/IncidentResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/IncidentResponseHistory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/IncidentQuestion.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/IncidentQuestionHistory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/IncidentResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/IncidentResponseHistory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/incidents/IncidentResourceIntTest.kt
This scenario was noticed during migration
=> SDIT-1421 Allow Missing response to incident question to mirror Nomis data

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/appointments/AppointmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/appointments/AppointmentsResourceIntTest.kt
Reverts ministryofjustice/hmpps-nomis-prisoner-api#636
=> Revert "SDIT-1551 In-cell appointments not working"

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/appointments/AppointmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/appointments/AppointmentsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt
SDIT-1551 In-cell appointments not working - use cell location
=> SDIT-1551 In-cell appointments not working

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/audit/AuditInterceptor.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AgencyInternalLocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/repository/StoredProcedureRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/LocationsResourceIntTest.kt
Reverts ministryofjustice/hmpps-nomis-prisoner-api#648
=> Revert "SDIT-1586 Audit call failure results in DB inconsistency"

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/LocationResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/LocationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/CourseActivity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/LocationsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitServiceTest.kt
Get extra convenience info from the location GET - parent description
=> SDIT-1522 Location From Nomis sync

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderAlert.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderAlert.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBooking.kt
Populated when the alert and an associated Staff account for the created or modify usernames
=> SDIT-1613 Add create and modify display name for Alerts

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/MergeTransactionRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonerService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResourceIntTest.kt
It appears that either OFFENDER_ID_DISPLAY_1 or OFFENDER_ID_DISPLAY_2 can point to the retained offender no. So search by either number and check which is retained via the OFFENDERS table
=> SDIT-1625 Calculate retained offender no

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResourceIntTest.kt
Since this is the core migration entity for alerts
=> SDIT-1645 NOMIS_ALERTS access for /prisoner/ids

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderBooking.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt
Needed by DPS to determine if this is associated with latest booking
=> SDIT-1643 Add booking sequence to alerts endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderBooking.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderExternalMovement.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentsResourceIntTest.kt
This will be passed to the DPS service so they don't need to make an additional call to retrieve this data.
=> SDIT-1704 Add prison id to sentence adjustments endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/PayRatesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/PayRateServiceTest.kt
Copy an updated end date of an activity to its current pay rates under certain conditions.
=> SDIT-1605 Activities sync, add end date problem

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt
Essentially this returns alerts that would have been migrated but just the active ones
=> SDIT-1730 Endpoint for active alerts for reconciliation

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt
…
Synchronisation service needs to know if this alert should be pushed to DPS if it does not exist. This is determined by the rules that were used to determine if it had been migrated. Typically, an alert that is missing from latest booking.
=> SDIT-1730 Get Alert indicates if this is a relevant alert from previous booking

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonerService.kt
Previous version did an n+1 to load the booking
=> SDIT-1753 Improve performance of get prisoner ids

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsReferenceDataService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AlertCode.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AlertType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/IEPLevel.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/ReferenceCode.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsServiceTest.kt
Updated AlertType and AlertCode classes to allow adding additional attributes. Also, added methods 'createAlertCode' and 'createAlertType' in AlertsResource class to create new alert codes/types. Added new service AlertsReferenceDataService to handle the creation of alert codes and types.
=> SDIT-1785 Add ability to create alert codes and types

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsReferenceDataService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/integration/OpenApiDocsTest.kt
Also fix flay OpenAPI test by allowing up to 10 seconds wait time
=> SDIT-1785 Added functionality to update alert codes and types status

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsServiceTest.kt
Tidy up references and removed endpoints no longer used
=> SDIT-1475 Remove retrieval of alerts from previous bookings

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Offender.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderBookingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AllocationResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsHearingResultAwardResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsHearingResultsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/appointments/AppointmentsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/core/DocumentResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Alias.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/NomisData.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Offender.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBookingBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/incentives/IncentivesResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/incidents/IncidentResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/ActivityRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/CaseNoteRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/IncentiveRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/VisitRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/nonassociations/NonAssociationsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisonerprofile/PrisonerProfileIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitResourceIntTest.kt
Provide a correct prisoner 'get all bookings' function and deprecate the 'bookings' list
=> SDIT-1660 OffenderBooking/Offender JPA model cascading delete error

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderCaseNoteRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesResourceIntTest.kt
Switch from booking to prisoner based fetching
=> SDIT-1799 Create standard set of casenotes Nomis api endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
possibly temporary synchronisation of Court case without an associated appearance
=> SDIT-1902 allow creation of court case without appearance

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitResourceIntTest.kt
=> SDIT-1508 Detect duplicate visits

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/config/NomisPrisonerApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/data/Exceptions.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitResourceIntTest.kt
Synchronisation service needs to know the existing visitId
=> SDIT-2026 Return existing visitId for 409 duplicate

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderCaseNote.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderCaseNote.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/CaseNoteRepositoryTest.kt
Add extra fields described in MICN-128
=> SDIT-1898 Switch mock casenotes-api to real one (from Nomis)

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderVisitBalance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderContactPersonRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Contact.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/LegacyVisitBalanceBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBooking.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBookingBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/VisitBalance.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/VisitRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitResourceIntTest.kt
Since visits creates person and contact records moving exiting tests to use DSL makes it easier for teh contact work
TODO Need to also move visit creation to DSL
=> SDIT-2044 Move visit tests to use DSL

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Language.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Person.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/NomisData.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Person.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/incidents/IncidentResourceIntTest.kt
=> SDIT-2044 A few more fields to PERSON - language

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Address.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/PersonAddress.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Person.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/PersonAddress.kt
=> SDIT-2044 A few more fields to PERSON ADDRESS

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/VisitOrderVisitorRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitServiceTest.kt
Will wait 10 seconds then will throw exception, else this would wait indefinitely
=> SDIT-2053 Wait for visit order visitors lock to clear

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/VisitVisitorRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitService.kt
Will wait 10 seconds then will throw exception, else this would wait indefinitely
=> SDIT-2053 Wait for visit visitors lock to clear

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesServiceTest.kt
the date format has changed over time
=> SDIT-2058 Some older casenotes amendments fail to be identified

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/PersonRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt
Corrected midnight dates been filtered our
=> SDIT-2078 GET persons/ids for migration

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt
To avoid DTO names that match other API endpoints
=> SDIT-2089 Rename DTO classes to avoid clashes

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/PayRatesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/CourseActivityPayRate.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/PayRateServiceTest.kt
This reverts commit 21aba9ce5ef032ed9a97a534a8d460a0bb3a445e.
=> Revert "SDIT-2138 Handle start dates from activity pay rate updates (#907)"

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helpers/NomisAudit.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/NomisEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Person.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/NomisData.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Person.kt
* Create subclass NomisEntity for audit columns with same name
* Create function to convert to DTO
* Improve audit person test
TODO Use for all person contact entities
=> SDIT-2148 Refactor audit to allow reuse

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helpers/NomisAudit.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/NomisAuditableEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Person.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Phone.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/AddressRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/PhoneRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/AddressPhone.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Person.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/PersonAddress.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/PersonPhone.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitResponseTest.kt
Rename super class for readability
=> SDIT-2148 Add audit data for contact phone

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderContactPerson.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderPersonRestrict.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/PersonEmployment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/PersonIdentifier.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/VisitorRestriction.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderPersonRestrictRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/PersonEmploymentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/PersonIdentifierRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/VisitorRestrictionRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Contact.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/ContactRestriction.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBooking.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Person.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/PersonEmployment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/PersonIdentifier.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/VisitorRestriction.kt
person identifiers
person employments
person restrictions
contacts
contact restrictions
=> SDIT-2148 Add audit data for contacts

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helpers/NomisStaff.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Staff.kt
Return general username for entered restriction so that DPS can use username rather than NOMIS staffId
=> SDIT-2149 Contact restriction enter by username

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/AgencyInternalLocationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/LocationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/locations/LocationServiceTest.kt
Ensure multiple events for the same location are processed sequentially.
=> SDIT-2191 Race condition with multiple location events

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Person.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/SequenceGeneratorOrUseId.kt
Replace deprecated class with SequenceOrUseId
=> SDIT-2235 Create person endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/specification/ActiveBookingsSpecification.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonerService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResourceIntTest.kt
This might be after a data fix
=> SDIT-2320 Cpnsider end dated bookings that are active as not really active

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderCaseNote.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesResourceIntTest.kt
Fix created date field returned from get casenotes
=> SDIT-2248 Revised casenotes merge strategy

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/AddressPhoneRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/PersonPhoneRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt
and /persons/{personId}/address/{addressId}/phone
=> SDIT-2302 POST /persons/{personId}/phone 

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt
and
POST /persons/{personId}/restriction
=> SDIT-2305 - POST /persons/{personId}/contact/{contactId}/restriction

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt
Added pad validated - DPS might use this
=> SDIT-2295 - PUT /persons/{personId}/address/{addressId}

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Phone.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt
PUT /persons/{personId}/phone/{phoneId}
=> SDIT-2299 - PUT /persons/{personId}/address/{addressId}/phone/{phoneId}

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AllocationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/api/GetAllocationResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/GetAllocationResourceIntTest.kt
This reverts commit 6f51fcc129d9eee0e316f4018c13505ad3886ae1.
=> Revert "SDIT-2162 Include activity start date in allocation response (#999)"

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/corporates/CorporateService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/data/CodeDescription.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Caseload.kt
=> SDIT-2409 Core corporate details for GET /corporates/{corporateId}

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/coreperson/CorePersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/coreperson/CorePersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Offender.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/coreperson/CorePersonResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/NomisData.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Offender.kt
- **SDIT-2396: ✨ Switch race to ethnicity as that is the term NOMIS uses**
- **SDIT-2396: ✨ Add in mapping of birth country**
=> SDIT-2396: ✨ Add in mapping of birth country

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/casenotes/CaseNotesResourceIntTest.kt
Return all usernames for staff id
=> SDIT-2481 Case notes reconciliation username check can fail

src/test/resources/application-test.yml
For confirmation of oracle recommended settings see https://www.h2database.com/html/features.html#compatibility.
=> SDIT-2396: 🔨 Change test configuration to match oracle nulls high

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/corporates/CorporateResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/corporates/CorporateService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Corporate.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/corporates/CorporateResourceIntTest.kt
Reordered methods so easier to find
=> SDIT-2494 POST /corporates

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/corporates/CorporateResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/corporates/CorporateService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/corporates/CorporateResourceIntTest.kt
and PUT and DELETE /corporates/{corporateId}/web-address/{webAddressId}
=> SDIT-2512 POST /corporates/{corporateId}/web-address

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/corporates/CorporateResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/corporates/CorporateService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/CorporateTypeRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/corporates/CorporateResourceIntTest.kt
CorporateType have no identity; the code is part of the composite key
=> SDIT-2497 POST /corporates/{corporateId}/type

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/corporates/CorporateResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/corporates/CorporateService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/corporates/CorporateResourceIntTest.kt
Refreshes entire list since a type has no identity
=> SDIT-2498 PUT /corporates/{corporateId}/type

build.gradle.kts
Reverts ministryofjustice/hmpps-nomis-prisoner-api#1134
=> Revert "SDIT-2676: ⬆️  Upgrade hmpps spring boot plugin to 8.0.0"

build.gradle.kts
Reverts ministryofjustice/hmpps-nomis-prisoner-api#1137
=> Revert "Revert "SDIT-2676: ⬆️  Upgrade hmpps spring boot plugin to 8.0.0""

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt
Fix NPE when modify date is null
=> SDIT-2694 Endpoint to return merges court cases

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt
Required so when adding contacts we don't need to call getPerson that doesn't peform well when the person has 1000s of contacts
=> SDIT-2723 Endpoint to return contact

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/CourtEventCharge.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/LinkCaseTxn.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/LinkCaseTxnRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/main/resources/db/migration/V1_1106__LINK_CASE_TXNS.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/LinkCaseTxn.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/NomisData.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderCharge.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
The link case transaction is returned linked the court event charge that was created
=> SDIT-2772 Link case transaction mapping

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt
POST version replaces this endpoint
=> SDIT-2764 removed the deprecated PUT recall endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/MovementReason.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenceResultCode.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
Correct court event change outcome
=> SDIT-2817 Add court event for recall

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt
* Just change contract
* TODO implement the update and delete
=> SDIT-2817 Add court events for updates and deletes

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
Update and delete are slightly different so new endpoint
=> SDIT-2817 recall revert endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
* Clones Core case data held in DPS
* Clones case identifiers
TODO - clone the other case children
* Charges
* Appearances
* Appearance charges
* Sentences
* Terms
* Adjustments
=> SDIT-2982 Endpoint to clone court cases to latest booking

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/CourtEvent.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
* Clones Core case data held in DPS
* Clones case identifiers
* Clones Charges
* Clones Appearances
TODO - clone the other case children
* Appearance charges
* Court orders
* Sentences
* Terms
* Adjustments
=> SDIT-2982 Endpoint to clone court cases to the latest booking

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/BookingResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
TODO: scenario when the court appearance is added to a case on an old booking
=> SDIT-2982 Add nullable clonedCourtCases to the court appearance result.

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/finance/TransactionsResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/finance/TransactionsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/GeneralLedgerTransactionRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/finance/FinanceResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/NomisData.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBooking.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderCaseNote.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderTransaction.kt
Endpoints for reconciliation process for finance
=> SDIT-2962 Transaction reconciliation

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt
Final Experiment before documenting in test
=> SDIT-2982 Clone cases case statusUpdateDate fix

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt
Prep work for deriving linked cases etc
=> SDIT-2982 Clone cases case

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/appointments/AppointmentResponse.kt
Bad data means some fields have to be nullable
=> SDIT-2678 Appointment reconciliation fix
