ministryofjustice/hmpps-nomis-prisoner-api

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/data/VisitResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Address.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AddressPhone.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Person.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/PersonAddress.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/PersonPhone.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Phone.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/PersonAddressBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/PersonBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/VisitResourceIntTest.kt
* Had to some entity attributes up to constructor so we can create phone and addresses
* Builders can now create a person with addresses and phone numbers
* Visitor endpoint now returns the lead visitor (if exists) with name and phone numbers
=> SDI-192 Add phones numbers to lead visitor

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/data/VisitResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/VisitVisitor.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/service/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/VisitBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/resource/VisitResourceIntTest.kt
There are 3 outcome reason codes that do not exist in the NOMIS reference data table. This allows the code to still be returned to the called with a dummy description
=> SDI-192 Returned outcome code even if there is reference data link

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Visit.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/service/VisitService.kt
Interestingly the integration tests don't show these bugs since these fields are only used in NOMIS, I think I need another integration test that checks the state of the database rather as well as the data returned by endpoint.
=> SDI-385 Fixed issue where visit date not set

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentService.kt
When the create endpoint is called at the exact same time it is possible that one of the calls returns the ID of the wrong newly created adjustment, this ensures it always returns the ID of the one just created
=> SDIT-816 Return ID of specific created adjustment rather than last one

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/api/CreateActivityRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ScheduleResourceIntTest.kt
But ignore them for now - need to pass them in the calling service before we can start using
=> SDIT-838 Include course schedule ids update on requests

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceResourceIntTest.kt
E.g. when suspended after transfer, and possibly due to other Activities business rules.
=> SDIT-907 Allow creation of Nomis attendance from outside prison.

src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AllocationResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AttendanceResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ScheduleResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/appointments/AppointmentsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/AdjudicationIncidentBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/DSL.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBookingBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/incentives/IncentivesResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitResourceIntTest.kt
- Adjudication DSL interface now contains all defaults, with defaults moved from Builder constructor
- Repository reorganised into sections
- Helpers used in Tests (rather than in Builders) moved and renamed to use the convention of `get` rather than `lookup` to disiguish from Builder reference data lookups
=> SDIT-871 Reorganise test repository

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/PayRatesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/ActivityResourceIntTest.kt
Handles an edge case where the course start date is movedbefore the existing pay rates become active by adjusting the start date of the pay rates.
=> SDIT-916 Handle course start date moved back in time

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationIncident.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/AdjudicationIncident.kt
* Now sets created user on Incident since this is displayed in NOMIS
* Fix issues where root offender was not being retrieved so prisoners with aliases had "no bookings"
=> SDIT-969 Set created user and fix issue with prisoners with aliases

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationHearing.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationHearingResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationIncidentParty.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationInvestigation.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsResourceIntTest.kt
DPS requires additional data for migration
- User who created the witnesses and victims
- User who created a hearing result
- Date time the result was created
- The NOMIS sanction sequence
In addition only outcomes for the request charge are returned for multi-charge adjudications
=> SDIT-927 Additional adjudication data required by DPS

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationHearingResult.kt
It is possible in NOMIS for a adjudication award to point to a charge that has been deleted.
This causes an issue since hearings are related to all punishments awarded at that hearing including the "bad" ones.
This allows the bad data to not prevent other charges being loaded that are related to that hearing.
=> SDIT-1072 - fix for bad data where hearing award points at a deleted charge

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/CreateHearingResultAwardRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationHearingResultAward.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/AdjudicationHearingResultAwardRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsHearingResultAwardResourceIntTest.kt
Given an adjudication this will find the first award that is the same type of award that is being added. In practice this will always be an ADA (unless DPS rules change)
=> SDIT-1138 Set consecutive award

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderKeyDateAdjustment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/AdjustmentRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentsResourceIntTest.kt
This value gets passed all the way through the migration service to the mapping service; but that is expecting KEY-DATE
=> SDIT-1165 KEY_DATE now KEY-DATE so matches with mapping service

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/HearingResultAwardRequests.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/UpdateHearingResultAwardResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/audit/Audit.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsHearingResultAwardResourceIntTest.kt
Added endpoint that updates awards as a batch, this might create new ones, update existing ones and delete ones removed by DPS
TODO:
- Refactor create to avoid duplicate code
- Implement update of awards
- Implement delete of awards
This is pushed so the sync service can regenerate DTOs due to rename of DTO
=> SDIT-1161 Update awards with just the creates working for now

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationIncidentCharge.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsHearingResultsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsHearingsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/AdjudicationCharge.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/AdjudicationParty.kt
This makes this consistent with NOMIS behaviour an fixes and issue where migrated adjudications that have no hearings may also not have an offenceId generated yet - which would affect NART reporting.
=> SDIT-1240 Generated offence ids when creating hearings and evidence

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt
Way too hard to create test data for this case so rely on regression. The singe record in prod will be tested manually.
=> SDIT-1246 Fix single merge sanction that points to 2 bookings

helm_deploy/hmpps-nomis-prisoner-api/Chart.yaml, helm_deploy/values-dev.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
1 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `8 => 0 (8 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist.
The following IPs have been …
=> Migrating project to use groups in allowlist

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/AdjudicationHearingResultAward.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsResourceIntTest.kt
Extended adjudications to include a new field, 'createdDateTime', storing when the record was created. The AdjudicationService now returns this additional information in its response. Related unit tests have been updated accordingly to verify the state of this new field.
=> SDIT-1383 Add createdDateTime to adjudications and update tests

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/CourtCaseRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
Introduced a new query, getNextCaseSequence, in CourtCaseRepository for generating the next sequence number for a court case associated with an offender booking. This change enables handling multiple cases for the same prisoner. Added a corresponding test to check the functionality.
=> SDIT-1405 Add getNextCaseSequence query in CourtCaseRepository

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationChargeResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsResourceIntTest.kt
The AdjudicationService now shows whether a single adjudication has multiple charges through a new field 'hasMultipleCharges'. This field returns true if the adjudication's charges size is greater than one. Additionally, changes were made to the AdjudicationsResourceIntTest to test this new feature.
=> SDIT-1429 Add 'hasMultipleCharges' field to AdjudicationService

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationADAAwardSummaryResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationsADAAWardSummaryResourceIntTest.kt
Removed the usage of 'prisonIds' in the AdjudicationService, and its related test cases. This simplifies the adjudication summary response, as we no longer track and include the list of prisons attended during the booking in the response data.
=> SDIT-1453 Remove prisonIds from adjudication summary

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderAlert.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderAlert.kt
Builder was referencing an unsaved WorkFlow instance when adding logs - not sure how this previously worked
=> SDIT-1527 Unpin Hibernate after fixing builder.

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderSentenceAdjustment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentsResourceIntTest.kt
DPS can change the sentence that an adjustment is associated with. This propagates this change to NOMIS (though this is not something you can do via the NOMIS UI)
=> SDIT-1534 Update sentence adjustment related sentence

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AllocationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AllocationResourceIntTest.kt
Scenario is:
* prisoner allocated to a course in DPS
* later (at least next day), the pay band was changed in DPS
* the same day as the pay band change the prisoner was released
* the next day the deallocation reason was updated in DPS
This caused us to write a duplicate of the expired pay band, so the insert failed with a data integrity issue and the event was rejected.
We now just leave the pay bands alone if the allocation is expired.
=> SDIT-1582 Handle updates to expired allocations

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/PayRatesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/PayRateServiceTest.kt
Scenario:
* we have a pay rate that has a future end date
* we receive an update to change the value of the pay rate and remove the end date
* the existing rate's end date isn't updated, so in NOMIS it appears to be active when it's not
The fix is to end the existing pay rate today and start the new one from tomorrow.
=> SDIT-1590 Fix bug with pay rate sync for future ended rate

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderKeyDateAdjustmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderSentenceAdjustmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentsResourceIntTest.kt
An option has been added to the sentencing adjustments API to return both active and all adjustments based on a new parameter, 'activeOnly'. This allows users to fetch all sentencing adjustments, regardless of their active status. The default behavior remains to return only active adjustments. Relevant testing has been adapted and expanded.
=> SDIT-1591 Add option to fetch all sentencing adjustments

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt
A new endpoint [/prisoners/booking-id/{bookingId}/alerts/{alertSequence}] has been created to allow deletion of specific alerts tied to prisoners' booking IDs. The new function 'deleteAlert' in the 'AlertsService' performs this operation, and appropriate tests on the function and its security have been established in 'AlertsResourceIntTest'. Corresponding changes were also made in 'AlertsResource'.
=> SDIT-1595 Add alert deletion functionality to API

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderAlertRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt
Introduced the ability to fetch alerts by filtering through a specific date range. The backend API now supports retrieving alerts from a 'fromDate' to a 'toDate'. Enhancements were made to the AlertsService and OffenderAlertRepository to facilitate this feature. Corresponding tests were also added. Changes also include an endpoint creation for retrieving alert Ids by applying a filter.
=> SDIT-1612 Implement alert filtering by date range

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonerService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResourceIntTest.kt
NOMIS Merge and DB use confusing names, these new names better represent the final state  of the various IDs
=> SDIT-1625 Rename merge properties

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderBooking.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/specification/OffenderWithBookingsSpecification.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonerService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Offender.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResourceIntTest.kt
…
The endpoint has an unfortunate parameter of `active` where setting this false means return active and inactive prisoners.
A prisoner is defined as someone at some-point that had a booking.
Also amened DSL to allow adding of Alias offender records.
=> SDIT-1645 Amended /prisoners/ids to return all prisoners not just active ones.

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsServiceTest.kt
DPS Rules defined as:
Identical datetime logic (V1):
If more than one of the most recent alerts have the same datetime. 
We use the following rules: 
* If one active alert exists in this subset, we surface that active alert.
*  If more than one identical active alerts exist, we surface the active alert with the most recent audit datetime. 
* If no active alerts exist in the subset, we surface the alert with the most recent audit datetime. 
* If audit datetime is the same for more two or more alerts in either point 1 or 2 then we surface all alerts with the same audit datetime.
=> SDIT-1659 Previous alert of same type rules

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsServiceTest.kt
When selecting a precious bookings alerts (when that alert does not appear on latest booking) when two or more alerts of the same type exist choose the active one. This is an edge case since in normal circumstances the active would be the latest there are 2 scenarios where  this is not the case:
* A merge between two prisoners that have the same alert
* The NOMIS alert data was loaded outside the NOMIS screens (very old alerts)
=> SDIT-1699 Active alerts take precedence on inactive

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/MergeTransactionRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisoners/PrisonersResourceIntTest.kt
Cancelled ones were also being returned causing the adjudication reconciliation job to double the number of adjudications per booking
=> SDIT-1820 Only return merges that have COMPLETED

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/VisitRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitResourceIntTest.kt
Check we can detect a duplicate visits efficiently by outputting telemetry. Next phase will be to reject the visit with a 409
=> SDIT-1508 Detect duplicate visits

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisonperson/PrisonPersonService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBooking.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderExternalMovement.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/prisonperson/PrisonPersonIntTest.kt
In NOMIS we found some inactive bookings without an end date - we were sending these null booking end date, but we should have sent them the last release date.
=> SDIT-2029 Fix migration bug

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitServiceTest.kt
outcomeReasonCode is immutable but the shadow outcomeReason is read-only
=> SDIT-1192 Do not set update immutable outcomeReason on visit visitor

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/VisitOrderVisitor.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/visits/VisitService.kt
This might mitigate the locking on visit order visitor table
Not convinced this will fix the issue, but should reduce the occurrences since no DELETE will happen if no visitors removed.
=> SDIT-2053 Switch to mutating visit order list rather than recreating

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/Person.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/PersonEmployment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/NomisData.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Person.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/PersonEmployment.kt
biometrics not used in NOMIS
Corporates and corporate names are nullable on database but not via NOMIS - so make non-nullable
=> SDIT-2090 Remove biometrics and corrected corporate nullability

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt
Ensure new alerts have a different sequence to the ones being replaced. Else an existing mapping will exist, and we delete from DPS
=> SDIT-2336 Resynchronise alerts

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/contactperson/ContactPersonResourceIntTest.kt
Will return 204 for delete or if the entity does not exist. The exception is identifier that is a composite key so 404 for not found makes more sense if person is not found.
400 when the combination of child / parents entities do not match since this indicates a client coding issue.
=> SDIT-2301 Delete endpoints for all contact entities

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/adjudications/AdjudicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helpers/StringUtils.kt, src/main/resources/db/migration/V1_53__OFFENDER_ALERTS.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/alerts/AlertsResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helpers/TruncateToUtf8LengthTest.kt
Improve the truncate function to deal with multi-byte chars at the end of String.
Move to Util file as well so used for adjudications and alerts
=> SDIT-2369 Truncate Alert comment text to 4000

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/OffenderBookingRepository.kt
Needed since the booking filters seems to alter the order that Oracle returns the results by default; so order by in the sub-select so runnum() is guaranteed to work
=> SDIT-2384 Use sub-select GET /bookings/ids/latest-from-id

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/AllocationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderProgramProfile.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/CourseActivityRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/GetActivityResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/activities/GetAllocationResourceIntTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/CourseAllocation.kt
Reverting because I did some before and after tests one of the endpoints in preprod for a handful of prisons, and in some cases there were a LOT of additional activities included in the migration. I need to investigate these first before going live.
Thinking about it I should have just run the endpoint against preprod locally... I'll do that before putting this change back in.
This reverts commit d8ea7713b29508536c756aac8a4dce52d4b0adc5.
=> Revert "SDIT-2423 Migrate activities with allocations in the last 6 months (#1070)"

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/appointments/AppointmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/appointments/AppointmentsResourceIntTest.kt
I thought DPS were going to stop sending the customName field to us in all cases - in which case we'd need to add the internal schedule reason to the comment on our side. Turns out they are only going to stop sending custom name if it's the same as the internal schedule reason - so we have nothing to do on our side
=> SDIT-2553 revert appointment comment changes

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingAdjustmentsResourceIntTest.kt
Original fix was to toggle the status of adjustments that are 0 days to inactive so the DPS CRDS ignores them. This caused a secondary issue for some adjustments; instead DPS CRDS will be changed to ignore the TO DATE for zero day adjustments. The TO DATE will continue not to be written for zero day adjustments since that makes more sense than have a TO DATE before the FROM DATE that was the previous functionality.
=> SDIT-2518 Zero days adjustments - keep status

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/CourtCase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
Only return cases created by the system so if merge event is delayed and a new case is created we won't return it
=> SDIT-2694 Endpoint to return merges court cases

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
When recalling not all sentences get converted to the same type, so this is a breaking change.
Also changed to POST since event though the implementation is a update it is actually more like a created. Also we need to PUT for update the recall.
Kept deprecated version until I update the sync service. Converted to test to only test new endpoint
=> SDIT-2764 Changed recall to accept a list of recall sentence types

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
It would be nice to have POST, PUT, DELETE but since in all 3 DPS recall operations in each case we are actually updating existing sentences in a batch; so we have POST and two versions of PUT operations with a slightly different bodies.
Also, refactor to reduce duplicate code
=> SDIT-2764 Add PUT recall and PUT /recall/restore-original

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/CourtCase.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/OffenderCharge.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/LinkCaseTxn.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/OffenderBooking.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/helper/builders/Repository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
Expose bug for linked cases where we cannot clone due to sourceCase no longer pointing at offender charge that is still on a court event
Will then fix bug - but setting up linked cases data is a large job in itself
TODO - clone the other case children
* Linked cases links
* Adjustments
=> SDIT-2982 Endpoint to clone court cases to the latest booking

src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/jpa/repository/CourtOrderRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/repository/CourtOrderIInsertRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/nomisprisonerapi/sentencing/SentencingResourceIntTest.kt
When multiple update charge events are received for a single appearance at the same time there is a race conditioning meaning multiple orders can be created for the same appearance. This is legal in NOMIS but not quite what we want.
Allow reading of the first order when there are multiples.
NOMIS allows multiple orders per event, but it is rare. We ensure we don't create multiples when several update events are received at the same time by using a SQL insert with a `where` clause on event_id
=> SDIT-3064 Ensure only one order is created per court appearance.
